---
apiVersion: v1
kind: Service
metadata:
  name: permanent-database
  labels:
    project: end-project
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    project: end-project
