---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    project: end-project
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    project: end-project
