---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    project: end-project
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    project: end-project 
